### ISSUE TITLE
lint error

### ISSUE THREAD

**Issue by EngrEric** [Enye-Cohort-1/Agroeasy#13]
lint is only correcting errors inside the src folder/directory.
I tried to use it by changing the "lint": "eslint src" script in package.json to other directories.
How do i include more than one directory?

**Comment by Way2nnadi** [comment]
Just add the name of the file or directory after `src`
```
...
"lint": "eslint src [new file | new director]"
...
```
Reference this API documentation to see how to do it
- https://eslint.org/docs/user-guide/command-line-interface
